// 3 herbs 2 crystal , increment by 3 and 2? 
import java.util.Scanner;
public class Task2{
    public static void main(String[]args){
        Scanner sc = new Scanner(System.in); //takin input 

        System.out.println("Please Enter number of Herbs (H)"); // output msg
        int Herbs = sc.nextInt();

        System.out.println("Please Enter number of Crystals (C)");
        int Crystals = sc.nextInt();

        
    }
}